### ISSUE TITLE
Can't delete report of the report has an error

### ISSUE THREAD

**Issue by mpr555** [Icinga/icingaweb2-module-reporting#74] opened 2020-09-11 14:27 UTC
I am trying to delete a report, but it is giving me an error with the filter that  I used.

Other reports are fine.

Bet as I can't get into the report, I cannot delete it.

Can you let me know a workaround for this, please?

kind regards

max

**Comment by nilmerg** [comment] 2022-03-18 11:17
Duplicate of #113

**Closed by nilmerg** 2022-03-18 11:17 UTC
