### ISSUE TITLE
Can't enter textual datetime in timeframe editor

### ISSUE THREAD

**Issue by johannesst** [Icinga/icingaweb2-module-reporting#154] opened 2022-10-17 09:29 UTC
## Describe the bug

When I try to enter a textual datetime description in the editor it's not saved. If there is already a predefined textual datetime description it's discarded

## To Reproduce

1. Open "Reporting", then  "Reports", then  "Time Frames"
2. Select an existing time frame or create a new one:

3. Select Start or End field, try to enter textual datetime description

4. Leave the field

## Expected behavior

The textual datetime is checked for validity. If it's valid input it's saved otherwise an error message is displayed.

## Screenshots
![grafik](https://user-images.githubusercontent.com/965038/196139961-f5f6b814-c658-427d-bea0-e975f7894968.png)
![grafik](https://user-images.githubusercontent.com/965038/196140209-db6c66ec-fa58-4a43-89a9-def71a53fe71.png)
![grafik](https://user-images.githubusercontent.com/965038/196140035-9c3216a6-ce3b-41d7-91a4-d3614ad923e9.png)
![grafik](https://user-images.githubusercontent.com/965038/196140243-d4bbd12f-7572-441c-8a84-0fd6237bbcfd.png)

## Your Environment

* Module version: reporting 0.9.2 
* Dependent module versions:  idoreports 0.9.1
* Icinga Web 2 version and modules (System - About): Icinga Web 2 Version 2.9.5
* Web browser and version: Google Chrome 105.0.5195.127, Firefox 78.7.0esr
* Icinga 2 version used (`icinga2 --version`):  r2.13.2-1
* PHP version used (`php --version`): 7.4.3
* Server operating system and version: Ubuntu 20.04.5 LTS (Focal Fossa)

**Comment by yhabteab** [comment] 2023-01-24 15:54
Duplicate of #128

**Closed by yhabteab** 2023-01-24 15:54 UTC
Labels: bug
