### ISSUE TITLE
Total SLA is missing when exporting

### ISSUE THREAD

**Issue by mocdaniel** [Icinga/icingaweb2-module-reporting#120] opened 2022-03-24 10:50 UTC
## Describe the bug

`Total` SLA value as displayed within Icingaweb2 is not exported, only the specific values for different Hosts/Services.

## To Reproduce

1. Generate an export
2. Export as CSV/JSON/PDF
3. Check that `Total` SLA is not present

## Expected behavior

`Total` SLA should be exported as well.

## Screenshots

No screenshot, but a JSON export as generated by the module:

```json
[{"Hostname":"icinga-web2","Service Name":"icinga_url_icingaweb2","Month":"2022-01","SLA in %":100},{"Hostname":"icinga-web2","Service Name":"icinga_url_icingaweb2","Month":"2022-02","SLA in %":100},{"Hostname":"icinga-web2","Service Name":"icinga_url_icingaweb2","Month":"2022-03","SLA in %":100}]
```

## Your Environment

* Module version: 0.9.2

* Icinga Web 2 version and modules (System - About): v2.9.5
  * reactbundle: v0.9.0
  * ipl: v0.5.0
* Icinga 2 version used (`icinga2 --version`): 2.13.2-1
* PHP version used (`php --version`): 7.4.19
* Server operating system and version: RHEL8.5

**Comment by nilmerg** [comment] 2022-03-24 10:54
Duplicate of #65

**Closed by nilmerg** 2022-03-24 10:54 UTC
