### ISSUE TITLE
Unknown or incorrect timezone error when loading module web page

### ISSUE THREAD

**Issue by willfurnell** [Icinga/icingaweb2-module-reporting#75] opened 2020-11-12 16:53 UTC
## Describe the bug

An error - SQLSTATE[HY000]: General error: 1298 Unknown or incorrect time zone: '' - is occoured when first loading the reporting module after setting up the database backend. There's no mention of timezone requirements/setup in the documentation, hence reporting as a bug.

## To Reproduce

1. Connect the reporting module to the database
2. Load the reporting page

## Expected behavior

The reporting page loads normally

## Screenshots

```
SQLSTATE[HY000]: General error: 1298 Unknown or incorrect time zone: ''

#0 /usr/share/icingaweb2/modules/ipl/vendor/ipl/sql/src/Connection.php(313): PDO->prepare(String)
#1 /usr/share/icingaweb2/modules/reporting/library/Reporting/RetryConnection.php(13): ipl\Sql\Connection->prepexec(String, Array)
#2 /usr/share/icingaweb2/modules/ipl/vendor/ipl/sql/src/Adapter/Mysql.php(15): Icinga\Module\Reporting\RetryConnection->prepexec(String, Array)
#3 /usr/share/icingaweb2/modules/ipl/vendor/ipl/sql/src/Connection.php(166): ipl\Sql\Adapter\Mysql->setClientTimezone(Object(Icinga\Module\Reporting\RetryConnection))
#4 /usr/share/icingaweb2/modules/ipl/vendor/ipl/sql/src/Connection.php(311): ipl\Sql\Connection->connect()
#5 /usr/share/icingaweb2/modules/reporting/library/Reporting/RetryConnection.php(13): ipl\Sql\Connection->prepexec(String, Array)
#6 /usr/share/icingaweb2/modules/ipl/vendor/ipl/sql/src/Connection.php(330): Icinga\Module\Reporting\RetryConnection->prepexec(String, Array)
#7 /usr/share/icingaweb2/modules/reporting/application/controllers/ReportsController.php(43): ipl\Sql\Connection->select(Object(ipl\Sql\Select))
#8 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Reporting\Controllers\ReportsController->indexAction()
#9 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#10 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#11 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#12 /usr/share/php/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
#13 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#14 {main}
```

## Your Environment

* Module version: latest git commit
* Dependent module versions: 
idoreports: latest commit, reactbundle: 0.7.0, pdfexport: latest commit, ipl: 0.4.0
* Icinga Web 2 version and modules (System - About):
Icinga Web 2 Version
    2.8.2
Git commit
    8a89839af94a247ee2149b2336c73b8251b477c0
PHP Version
    7.3.11
Git commit date
    2020-08-17
* Icinga 2 version used (`icinga2 --version`):
1.12.1
* Server operating system and version:
CentOS 7
* MySQL/MariaDB version
10.3.15-MariaDB-log (galera cluster)

## Additional context
N/A

**Comment by willfurnell** [comment] 2020-11-24 10:10
Just to add that I've added UTC as my PHP timezone, still with no luck. Is anyone able to help please?

**Comment by nilmerg** [comment] 2020-11-24 14:29
Hi,

this doesn't seem to an issue with how the module tries to to setup the timezone. I know it seems obvious at first by looking at the traceback, though the final call to `PDO::prepare()` shouldn't execute the statement and therefore the module even hasn't had a chance to tell the server which timezone to use.

To me this looks that the statement is either instantly executed (which shouldn't be the case, unless you have a customized PDO extension) or that the **server's** default timezone is broken. (or the one of the database) Maybe check whether you've configured the default timezone for the server/database correctly. (I can't help you with this though, if you need assistance with this, please [ask in the forums for it](https://community.icinga.com/).)

**Comment by willfurnell** [comment] 2020-12-01 13:29
As far as I can see the default time zone for the server is configured as SYSTEM, and the time zone functionality is working...

```MySQL [(none)]> select now();
+---------------------+
| now()               |
+---------------------+
| 2020-12-01 13:26:17 |
+---------------------+
1 row in set (0.00 sec)

MySQL [(none)]> select @@global.time_zone;
+--------------------+
| @@global.time_zone |
+--------------------+
| SYSTEM             |
+--------------------+
1 row in set (0.01 sec)

MySQL [(none)]> select @@session.time_zone;
+---------------------+
| @@session.time_zone |
+---------------------+
| SYSTEM              |
+---------------------+
1 row in set (0.00 sec)
```
As far as I can see SYSTEM is a valid default time zone. Does this module need it to be another value?

**Comment by nilmerg** [comment] 2020-12-02 07:28
No, neither Icinga Web 2 nor the reporting module have any requirement in this regard. (Besides the timezone in `php.ini`, but that has no effect for SQL anyway)

**Comment by willfurnell** [comment] 2020-12-08 09:11
Just an update, `@@global.time_zone` and `@@session.time_zone` have now been set to 'Europe/London', but we're still getting exactly the same error from the reporting module web UI. I'm not sure what else we can change server side?

**Comment by willfurnell** [comment] 2020-12-08 09:16
Also to note the same error occours when running `icingacli reporting` from the command line:

```
icingacli reporting
ERROR: PDOException in /usr/share/icingaweb2/modules/ipl/vendor/ipl/sql/src/Connection.php:313 with message: SQLSTATE[HY000]: General error: 1298 Unknown or incorrect time zone: ''
```

**Comment by jeephammer** [comment] 2021-01-04 14:20
Hello nilmerg

I'm putting additional details regarding our Icinga environment configuration:

- Icinga2 and Icinga2 reporting are both connected to our Galera Cluster environment using the ProxySQL load balancer.  The timezone error is recorded on the proxysql log, but not on the database server log:

2021-01-04 13:52:47 MySQL_Session.cpp:2278:handler_again___status_SETTING_GENERIC_VARIABLE(): [WARNING] Error while setting time_zone to "" on dummy.example.com:3306 hg 2 :  1298, Unknown or incorrect time zone: ''
2021-01-04 13:52:47 MySQL_Session.cpp:135:kill_query_thread(): [WARNING] KILL CONNECTION 95 on dummy.example.com:3306

(I changed the hostname due to security reasons).

According to the ProxySQL documentation:
"...
If the client explicitly sets a supported variable, ProxySQL will ensure that said variable is configured on the backend connection as well.
    If the client does not explicitly set a supported variable, ProxySQL won’t configure the variable on the backend connection. That is: if the client doesn’t set a value for a variable, it will use whatever value is configured on the backend connection
...https://assets.grammarly.com/emoji/v1/1f3af.svg
"
Is there any way to specify the MySQL client time zone from an Icinga session so that the ProxySQL can detect the default timezone value?

Regards

**Comment by nilmerg** [comment] 2021-01-25 08:07
Hi jeephammer,

as described early on, I don't think the issue is tied to what is defined for the connection. Though, I have no ProxySQL and can only guess here. So you could try adjusting [what the module uses as SQL timezone](https://github.com/Icinga/ipl-sql/blob/master/src/Adapter/Mysql.php#L17) (in `/usr/share/icingaweb2/modules/ipl/vendor/ipl/sql/src/Adapter/Mysql.php`) and see if that happens to solve the issue.

Though, again, the traceback posted in the OP tells me that this part of the code is trying to tell the server which time zone to use. That's when things go wrong, but not because what time zone it is, but because it's transmitting a prepared query without the actual time zone. That's not been transmitted at that time yet. So the server (or ProxySQL) sees `SET time_zone = ?` and complains without waiting for the time zone it seems. To me. And now knowing you have a middle-ware between Icinga Web 2 and the database this doesn't look as impossible at it did early on. :thinking:

**Comment by willfurnell** [comment] 2021-01-27 11:47
Interestingly when removing the ProxySQL component, and connecting directly to one of the database servers in the cluster this issue goes away.

I will give editing `Mysql.php` a go as it would be nice to have our database for this clustered rather than on one machine.

**Comment by nilmerg** [comment] 2022-03-18 13:27
Closing here. We can't fix what's caused by a middleware.

**Closed by nilmerg** 2022-03-18 13:27 UTC
