### ISSUE TITLE
New Timeframe not saved / values are delete

### ISSUE THREAD

**Issue by Bastilla123** [Icinga/icingaweb2-module-reporting#172] opened 2023-01-09 07:18 UTC
## Describe the bug

I want to create a new Timeframe. First Try i insert over datetime picker 2023-01-04 00:00:00 - 2023-01-06 23:59:59. This values are insert in field BUT when i click inside this fields and then change focus to another field complete value is delete.

Next thing i insert over datetime picker 2023-01-04 00:00:00 - 2023-01-06 23:59:59 and then on button save. No exception nothing BUT in database i can't found a new entity also in Listview of Timeframe it is missing.

Last thing i want to insert in Start such things like now or Current Day. I insert it after focus change value is instant delete...

## To Reproduce

Steps are describe in Bugdescription

## Expected behavior

I can insert textvalues without it is delete instant. I can create a new timeframe.

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.9.5
* Web browser and version: Edge x64  108.0.1462.76
* Icinga 2 version used (`icinga2 --version`):  r2.13.2-1
* PHP version used (`php --version`): PHP 7.4.30
* Server operating system and version: Ubuntu 22.04.1 LTS
* ido reports: 0.9.1
* reporting: 0.10.0

**Comment by yhabteab** [comment] 2023-01-16 12:47
Maybe duplicate of #154

**Comment by yhabteab** [comment] 2023-01-24 15:55
Duplicate of #128

**Closed by yhabteab** 2023-01-24 15:55 UTC
Labels: bug
